apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydpyellow
  annotations:
    kubernetes.io/change-cause: "Deploy to yellow"

spec:
  minReadySeconds: 5
  replicas: 6

  selector:
    matchLabels:
      app: yellow-app

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      name: myyellowpods
      labels:
        app: yellow-app

    spec:
      containers:
        - name: myyellow-containers
          image: longflew/ingress:YELLOWPAGE
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mystorageaws
              mountPath: /usr/share/nginx/html

      volumes:
        - name: mystorageaws
          persistentVolumeClaim:
            claimName: mypvc-blueapp